# Generated by Django 2.2.11 on 2020-04-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Название')),
                ('text', models.TextField(max_length=1280, verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
